# Copyright 2022-present, Lorenzo Bonicelli, Pietro Buzzega, Matteo Boschini, Angelo Porrello, Simone Calderara.
# All rights reserved.
# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.

best_args = {
    'seq-mnist': {
        'er': 
           {
               200: {'lr': 0.01,
                     'minibatch_size': 10,
                     'batch_size': 10,
                     'n_epochs': 1},
               500 : {'lr': 0.01,
                     'minibatch_size': 128,
                     'batch_size': 128,
                     'n_epochs': 10},

               1000: {'lr': 0.01,
                     'minibatch_size': 128,
                     'batch_size': 128,
                     'n_epochs': 10},

               5120: {'lr': 0.01,
                     'minibatch_size': 128,
                     'batch_size': 128,
                     'n_epochs': 10},
            },
        'gem': {200: {'lr': 0.01,
                      'gamma': 1.0,
                      'batch_size': 128,
                      'n_epochs': 10},
                500: {'lr': 0.03, 'gamma': 0.5, 'batch_size': 128,
                      'n_epochs': 10},
                1000: {'lr': 0.01, 'gamma': 1.0, 'batch_size': 128,
                       'n_epochs': 10},
                5120: {'lr': 0.01, 'gamma': 1.0, 'batch_size': 128,
                       'n_epochs': 10}},
        'agem': {200: {'lr': 0.01,
                       'minibatch_size': 128,
                       'batch_size': 128,
                       'n_epochs': 10},
                 500: {'lr': 0.01,
                       'minibatch_size': 128,
                       'batch_size': 128,
                       'n_epochs': 10},
                 1000: {'lr': 0.01,
                       'minibatch_size': 128,
                       'batch_size': 128,
                       'n_epochs': 10},
                 5120: {'lr': 0.01,
                        'minibatch_size': 128,
                        'batch_size': 128,
                        'n_epochs': 10}},
        'icarl': {200: {'lr': 0.01,
                        'minibatch_size': 128,
                        'optim_wd': 0,
                        'batch_size': 128,
                        'n_epochs': 10},
                  500: {'lr': 0.01,
                        'minibatch_size': 128,
                        'optim_wd': 0,
                        'batch_size': 128,
                        'n_epochs': 10},
                  1000: {'lr': 0.01,
                        'minibatch_size': 128,
                        'optim_wd': 0,
                        'batch_size': 128,
                        'n_epochs': 10},
                  5120: {'lr': 0.01,
                         'minibatch_size': 128,
                         'optim_wd': 0,
                         'batch_size': 128,
                         'n_epochs': 10}},
      },
    'seq-cifar10': {
                    'er': {200: {'lr': 0.1,
                                 'minibatch_size': 32,
                                 'batch_size': 32,
                                 'n_epochs': 50},
                           500: {'lr': 0.1,
                                 'minibatch_size': 32,
                                 'batch_size': 32,
                                 'n_epochs': 50},
                           1000: {'lr': 0.1,
                                 'minibatch_size': 32,
                                 'batch_size': 32,
                                 'n_epochs': 50},
                           5120: {'lr': 0.1,
                                  'minibatch_size': 32,
                                  'batch_size': 32,
                                  'n_epochs': 50}},
                    'gem': {200: {'lr': 0.03,
                                  'gamma': 0.5,
                                  'batch_size': 32,
                                  'n_epochs': 50},
                            500: {'lr': 0.03, 'gamma': 0.5,
                                  'batch_size': 32,
                                  'n_epochs': 50},
                            1000: {'lr': 0.03, 'gamma': 0.5,
                                  'batch_size': 32,
                                  'n_epochs': 50},
                            5120: {'lr': 0.03, 'gamma': 0.5,
                                   'batch_size': 32,
                                   'n_epochs': 50}},
                    'agem': {200: {'lr': 0.03,
                                   'minibatch_size': 32,
                                   'batch_size': 32,
                                   'n_epochs': 50},
                             500: {'lr': 0.03,
                                   'minibatch_size': 32,
                                   'batch_size': 32,
                                   'n_epochs': 50},
                             1000: {'lr': 0.03,
                                   'minibatch_size': 32,
                                   'batch_size': 32,
                                   'n_epochs': 50},
                             5120: {'lr': 0.03,
                                    'minibatch_size': 32,
                                    'batch_size': 32,
                                    'n_epochs': 50}},
                    'icarl': {200: {'lr': 0.1,
                                    'minibatch_size': 0,
                                    'softmax_temp': 2.0,
                                    'optim_wd': 0.00001,
                                    'batch_size': 32,
                                    'n_epochs': 50},
                              500: {'lr': 0.1,
                                    'minibatch_size': 0,
                                    'softmax_temp': 2.0,
                                    'optim_wd': 0.00001,
                                    'batch_size': 32,
                                    'n_epochs': 50},
                              1000: {'lr': 0.1,
                                    'minibatch_size': 0,
                                    'softmax_temp': 2.0,
                                    'optim_wd': 0.00001,
                                    'batch_size': 32,
                                    'n_epochs': 50},
                              5120: {'lr': 0.03,
                                     'minibatch_size': 0,
                                     'softmax_temp': 2.0,
                                     'optim_wd': 0.00001,
                                     'batch_size': 32,
                                     'n_epochs': 50}},
                    'der': {200: {'lr': 0.03,
                                  'minibatch_size': 32,
                                  'alpha': 0.3,
                                  'batch_size': 32,
                                  'n_epochs': 50},
                            500: {'lr': 0.03,
                                  'minibatch_size': 32,
                                  'alpha': 0.3,
                                  'batch_size': 32,
                                  'n_epochs': 50},
                            1000: {'lr': 0.03,
                                  'minibatch_size': 32,
                                  'alpha': 0.3,
                                  'batch_size': 32,
                                  'n_epochs': 50},
                            5120: {'lr': 0.03,
                                   'minibatch_size': 32,
                                   'alpha': 0.3,
                                   'batch_size': 32,
                                   'n_epochs': 50}}
            }

     }